services:

  # Serviço do MongoDB
  db_service:
    container_name: db_descubra_service
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: db_descubra
    volumes:
      - ./config-db.js:/docker-entrypoint-initdb.d/config-db.js:ro
    ports:
      - 27017:27017
